apiVersion: v1
kind: Service
metadata:
  name: express-app-service
spec:
  selector:
    app: express-app # This connects the Service to the Pods with this label
  ports:
    - protocol: TCP
      port: 80 # The port exposed by the Service internally in the cluster
      targetPort: 3000 # The port your Express app container is listening on
  type: LoadBalancer # Use ClusterIP for internal only, LoadBalancer to expose externally (if supported by your cloud)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
  labels:
    app: express-app
spec:
  replicas: 1 # Number of instances you want running
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "opentelemetry-operator-system/elastic-instrumentation"
    spec:
      containers:
      - name: express-app-container
        image: alessandrobrofferio273/my-server-synth:v8
        ports:
        - containerPort: 3000 # The port your Express app listens on
        env:
        - name: NODE_ENV
          value: "production"